### ISSUE TITLE
unexpected "-", expecting letter

### ISSUE THREAD

**Issue by j1elo** [tajmone/pandoc-goodies#9] opened 2019-07-03 11:04 UTC
The GitHub template cannot be used as it generates a parsing error. System is Ubuntu 16.04 LTS (Xenial), and Pandoc version is 1.16. Full information with following commands:

```sh
# Version info
# ------------

grep DESCRIPTION /etc/lsb-release 

#> DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"

pandoc --version | head -1

#> pandoc 1.16.0.2


# Failure test
# ------------

git clone https://github.com/tajmone/pandoc-goodies.git

cat <<EOF >test.md
# Section 1
This is a Markdown document!

# Section 2
This is section 2
EOF

pandoc -f markdown -t html5 --toc \
    --template pandoc-goodies/templates/html5/github/GitHub.html5 \
    -o test.html test.md

#> pandoc: "template" (line 1, column 2):
#> unexpected "-"
#> expecting letter
```

I'd understand that the 16.04 system is a bit old (albeit fully supported). However the error also happens in the latest stable version, Ubuntu 18.04 LTS (Bionic):

```sh
# Version info
# ------------

grep DESCRIPTION /etc/lsb-release 

#> DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

pandoc --version | head -1

#> pandoc 1.19.2.4


# Failure test
# ------------

git clone https://github.com/tajmone/pandoc-goodies.git

cat <<EOF >test.md
# Section 1
This is a Markdown document!

# Section 2
This is section 2
EOF

pandoc -f markdown -t html5 --toc \
    --template pandoc-goodies/templates/html5/github/GitHub.html5 \
    -o test.html test.md

#> pandoc: "template" (line 1, column 2):
#> unexpected "-"
#> expecting letter
#> CallStack (from HasCallStack):
#>   error, called at src/Text/Pandoc/Templates.hs:73:35 in pandoc-1.19.2.4-HbfKWUyODESBIy0vGktOwX:Text.Pandoc.Templates
```

Which means that it's not possible to use the template even with latest stable version of Ubuntu (and by extension I'd say Debian)

**Comment by tajmone** [comment] 2019-07-03 12:04
Hi @j1elo,

The template will only work with pandoc v2 or above — to be safe, you should use at least v2.1.1, as indicated in the template header. For each asset, the project indicates which version of pandoc and PP the asset was designed for and tested with. The idea is to try to stick to the latest version and use new features of both pandoc and PP.

The above error seems due to the pandoc template comment symbol `$--`, which was introduced in later versions of pandoc, and is not recognized by pandoc 1.16.

The pandoc goodies repository originally contained assets for pandoc v1, and when I migrated the repository to pandoc v2 I kept copy of the v1 assets in a `pandoc_v1/` subfolder; but it looks like there isn't a stored version of the GitHub template for with pandoc 1.

You can look at the blame history of the template and, if you really need to use pandoc v1, you could try and use the template from a older commit:

- https://github.com/tajmone/pandoc-goodies/blame/master/templates/html5/github/GitHub.html5

The earliest version of the template mentions in the comments that it works with pandoc v1.19.2:

- https://github.com/tajmone/pandoc-goodies/commit/2e29e9cd54bb9113c0b4fb474a07b8fcf6ee287b

If you can confirm to me if (and which) version of the GitHub template works fine with pandoc v1, I'll add a copy to a `pandoc_v1/` subfolder, so that anyone who needs to use pandoc v1 can use it. 

But I strongly advise you to use an updated version of pandoc 2.x — you're using pandoc 1.16.0.2, which is very old indeed.

**Comment by tajmone** [comment] 2019-07-05 15:20
@j1elo I'm closing this issue. If you have further questions, or feedback, feel free to reopen it.

**Closed as completed by tajmone** 2019-07-05 15:20 UTC

**Comment by j1elo** [comment] 2019-07-06 11:02
Hi, thanks for the detailed reply, I'll investigate the commits, following your advice.

The issue with this is that the official packages are rendered unusable (for at least one year and a half more, when 20.04 gets released) :-(

This was meant to be part of a small documentation I wanted to share with people, where the build instructions should be no more than `apt-get` installing a couple dependencies (I cannot expect anyone to install custom software downloaded from wherever). So I'll probably have to end up just using some Github-like CSS without the extra goodies of this template, for the sake of backwards compatibility.

Thanks anyway for sharing this!

**Comment by tajmone** [comment] 2019-07-06 20:47
> The issue with this is that the official packages are rendered unusable (for at least one year and a half more, when 20.04 gets released) :-(

But pandoc v2.0 has been around for quite a while now — v1 being obsolete. I would have though that v2 was the official package on most Linux distros:

https://pandoc.org/releases.html
